// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Chartmuseum) DeepCopyInto(out *Chartmuseum) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Chartmuseum.
func (in *Chartmuseum) DeepCopy() *Chartmuseum {
	if in == nil {
		return nil
	}
	out := new(Chartmuseum)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Chartmuseum) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartmuseumDependency) DeepCopyInto(out *ChartmuseumDependency) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartmuseumDependency.
func (in *ChartmuseumDependency) DeepCopy() *ChartmuseumDependency {
	if in == nil {
		return nil
	}
	out := new(ChartmuseumDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartmuseumList) DeepCopyInto(out *ChartmuseumList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Chartmuseum, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartmuseumList.
func (in *ChartmuseumList) DeepCopy() *ChartmuseumList {
	if in == nil {
		return nil
	}
	out := new(ChartmuseumList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChartmuseumList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartmuseumSpec) DeepCopyInto(out *ChartmuseumSpec) {
	*out = *in
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]ChartmuseumDependency, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartmuseumSpec.
func (in *ChartmuseumSpec) DeepCopy() *ChartmuseumSpec {
	if in == nil {
		return nil
	}
	out := new(ChartmuseumSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartmuseumStatus) DeepCopyInto(out *ChartmuseumStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartmuseumStatus.
func (in *ChartmuseumStatus) DeepCopy() *ChartmuseumStatus {
	if in == nil {
		return nil
	}
	out := new(ChartmuseumStatus)
	in.DeepCopyInto(out)
	return out
}
