apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cm-operator
  template:
    metadata:
      labels:
        name: cm-operator
    spec:
      containers:
        - name: cm-operator
          image: vtuson/cm-operator
          command:
          - cm-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CMSERVICE
              value: "chartmuseum-chartmuseum"
            - name: CMPORT
              value: "3000"
